### ISSUE TITLE
Problem with IE

### ISSUE THREAD

**Issue by 0x539-nero** [Mediawiki-wysiwyg/WYSIWYG-CKeditor#101]
I am getting a parsing error when posting in from Microsoft Word. I am using a second tier of bullet (points).

The picture below shows when I try to submit the change.

![image](https://cloud.githubusercontent.com/assets/19697472/22438770/cbedb9fc-e6f2-11e6-863e-f71386dcde26.png)

The IE version is 11.0.9600.18537.

Thank you very much for this great tool.

**Comment by 0x539-nero** [comment]
When pasting into Chrome it works fine.

**Comment by 0x539-nero** [comment]
I also have MW 1.26.

**Comment by riparap** [comment]
This error depends on contents of the text you are pasting from ms word into wysiwyg. I suspect it may have something to do with double quote characters inside double quoted strings of html (f.ex attribute strings, see #96). For some reason IE puts these into html code of page. With other browsers it will be single quotes inside double quoted strings so the produced html code is valid. Would it be possible for you to copy- paste the text that is causing this error here so that I could test it too (see #96 as an example).

**Comment by 0x539-nero** [comment]
Draft notes from today’s discussion:

Guidelines for test

•	test

•	test

o	test

o	test

o	test

o	test

o	test

o	test

o	test

[draft notes.docx](https://github.com/Mediawiki-wysiwyg/WYSIWYG-CKeditor/files/754982/draft.notes.docx)

**Comment by riparap** [comment]
In MW 1.28 and latest version of wysiwyg with IE, copy-paste of text and toggling source button does not create error. Text is accepted as html, it is not converted to bulleted list of wikitext code (I have Word 2016).

I have some old test bed for MW1.26.2 but I am not sure status of its database. There IE seems to produce your error with wysiwyg version 1.5.6_0 [B551+09.11.2016]. If I switch to use latest version of wysiwyg with MW1.26.2, copy-paste works in same way as with MW1.28 , it will not produce your error.

What version of wysiwyg are you using with your MW1.26? ... if you are not using latest version 1.5.6_0 [B551+09.02.2017] of wysywyg, could you try to test it with your wiki.

**Comment by riparap** [comment]
It seems that in pasted text (html format) there is style attribute for bullets. Wysiwyg seems not to be able to handle this properly when page is converted into wikitext mode (FF), for some reason extra `</ul>` tag will be added in text. This does not seem to create your error  but will mess up text anyway.

**Comment by 0x539-nero** [comment]
I will test the lastest build of WYSYWYG today and let you know how it worked out.

**Comment by 0x539-nero** [comment]
It works. Thank you very much riparap!

**Comment by riparap** [comment]
Did you use version "1.5.6_0 [B551+09.02.2017]" of branch wysiwyg_mw128 (with Ckeditor 4.5.9) or same version "1.5.6_0 [B551+09.02.2017]" but from branch wysiwyg_mw128_462 which contains upgraded CKeditor 4.6.2 ?

...so the error is now gone, good.
But did you try to:
1. copy contents of your test document draft notes.docx and paste it  into wysiwyg
2. press source button to change to wikitext mode
3. check the wikitext code... is there orphan `<\ul>` elements visible ?
4. press source button again to change to wysiwyg mode... is the contents of the page now different than what it was in step 1 ?

In my test with your draft notes.docx, I get orphaned `<\ul>` elements in wikitext mode and after switching back to wysiwyg mode, contents of page is not identical to original text anymore.

To me it looks like problem is the html code which is produced by paste action from word. It cointains multi- level nested `<ul>` and `<li>` elements with additional attributes in a way which seems to make wysiwyg confused. Wikitext does not support attributes in same way as html code. For this reason wysiwyg is trying to preserve text in html code. In this nested case of `<ul>` and `<li>` elements, the whole stucture should be preserved as html, now the first level is converted to wikitext and only the rest of the elements stay in html. There is anyway some kind of error which corrupts the structure when repeatedly toggling between wikitext and wysiwyg modes.  At this moment I have been unable to fix this properly...

**Comment by 0x539-nero** [comment]
```
Draft notes from today’s discussion:

&nbsp;

Guidelines for test

&nbsp;

*test 

&nbsp;

*test 

&nbsp;
<ul style="list-style-type: circle;">
<li>test</li>
</ul>

&nbsp;
<ul style="list-style-type: circle;">
<li>test</li>
</ul>

&nbsp;
<ul style="list-style-type: circle;">
<li>test</li>
</ul>

&nbsp;
<ul style="list-style-type: circle;">
<li>test</li>
</ul>

&nbsp;
<ul style="list-style-type: circle;">
<li>test</li>
</ul>

&nbsp;
<ul style="list-style-type: circle;">
<li>test</li>
</ul>

&nbsp;
<ul style="list-style-type: circle;">
<li>test</li>
</ul>

&nbsp;
```

**Comment by 0x539-nero** [comment]
I am using:

Version 1.5.6_0 [B551+09.02.2017].

**Comment by riparap** [comment]
Thanks for information. If that is produced wikitext code, then it looks ok except that there are extra `&nbsp;` tags. They do not cause problems but are little annoying. I have not been able to track source of them either. Strange thing is that in my test I get errors I tried to describe above. I guess the difference is that I used multilevel bullets you might have them on single level only.
