### ISSUE TITLE
Problems with loading in IE

### ISSUE THREAD

**Issue by 0x539-nero** [Mediawiki-wysiwyg/WYSIWYG-CKeditor#102]
It seems to be very slow loading the editor into IE.

I do notice when opening the console that I receive this when the editor is loading:

Use of "CKEDITOR_BASEPATH" is deprecated. Use mw.config instead.

Any thoughts?

**Comment by riparap** [comment]
Variable is used in core files of CKeditor which should be kept unmodified. It is also defined in php code, I am not sure how this should be fixed. At this moment that is just a warning which should not cause any problem.

Javascripts of wysiwyg are not minified. wysiwyg would run little faster if that would be done.

**Comment by 0x539-nero** [comment]
I have THE weirdest thing happening with IE...

When I have IE Developer Tools (F12) open --- the page loads fine (the editor)...

When I don't, the editor won't load. Any idea? Is this to do with the CKEDITOR_BASEPATH?

**Comment by 0x539-nero** [comment]
I fixed this!

Because our website is on our Intranet I unchecked the "Display intranet sites in Compatibility View".
