### ISSUE TITLE
Autolinking of external Sidebar-Links

### ISSUE THREAD

**Issue by ianp1** [Mediawiki-wysiwyg/WYSIWYG-CKeditor#111]
When opening the MediaWiki:Sidebar page with the CKeditor, external links get changed to a MediaWiki link. This effectively breaks the menu entry.
For example, the code
`**https://example.org |Link`
becomes 
`**[https://example.org https://example.org] |Link`
upon opening.
This should be changed to prevent unintentionally breaking menu entries.

**Comment by riparap** [comment]
Wysiwyg seems to do that, because https is interpreted as external link.
As workaround you have to exclude at least these two namespaces of mediawiki in your LocalSettings.php, so that they will be edited using editor of mediawiki instead:
```
#These are not compatible with WYSIWYG
$wgFCKEditorExcludedNamespaces[] = NS_MEDIAWIKI;
$wgFCKEditorExcludedNamespaces[] = NS_TEMPLATE;
```
