### ISSUE TITLE
Multiple <div class="mw-parser-output"> in B551+10.12.2017

### ISSUE THREAD

**Issue by Kukulkano** [Mediawiki-wysiwyg/WYSIWYG-CKeditor#112]
We're using the most recent released version B551+10.12.2017 but it creates more and more entries like

`<div class="mw-parser-output">`

if we save the pages. Sometimes, after some pages have been modified for several times, we have pages starting like this:
`<div class="mw-parser-output"><div class="mw-parser-output"><div class="mw-parser-output"><div class="mw-parser-output">...`

Is there a way to prevent the system from creating more and more of these entries? They are not visible but definitely not okay.

**Comment by riparap** [comment]
This has been fixed in Version 1.5.6_0 [B551+19.05.2018]   (in banch wysiwyg_mw130_462).
