### ISSUE TITLE
Editor (repeatedly) mangles valid links if they start with //

### ISSUE THREAD

**Issue by dev-zero** [Mediawiki-wysiwyg/WYSIWYG-CKeditor#13]
If a page contains the following links:

```
[//www.google.com A link to google]
```

the editor interprets it as a Wiki-Link and rewrites it after every edit to:

```
[[//www.google.com|A link to google]
```

until

```
[[[[[[[[//www.google.com|A|link|to|google]]]]]]]
```

Unfortunately the default Main_Page of a fresh Mediawiki installation contains such links, and they are valid syntax with the implication that the same protocol used to fetch the wiki-page will be prepended.

**Comment by riparap** [comment]
Fixing this is out of my comfort zone :), ... at this moment I do not know how to fix this, exept using "http://" in front of link text. Help is highly appreciated.

**Comment by riparap** [comment]
This was not so difficult in the end :)... It has been fixed.
