### ISSUE TITLE
Image plugin broken with mediawiki-1.23.x

### ISSUE THREAD

**Issue by dev-zero** [Mediawiki-wysiwyg/WYSIWYG-CKeditor#19]
When trying to insert an image using the image plugin, I end up with a `noimage.png` instead.

The bug must be somewhere in the `parse` method of the `CKeditorParser` class.
For the same `$term` in `wfSajaxGetImageUrl` the `parse` method returns different values.

Output from master + mediawiki-1.22.x:

```
[ckeditor] abc.jpg
[ckeditor] <p><img src="/mediawiki/img_auth.php/a/aa/abc.jpg" _fck_mw_filename="abc.jpg" alt="" /
```

Output from CKeditor_v4 + mediawiki-1.23.3:

```
[ckeditor] abc.jpg
[ckeditor] <p>[<a href="File:abc.jpg%7CFile:abc.jpg">[1]</a>]
```

when adding `wfDebugLog` statements code in `wfSajaxGetImageUrl` as follows:

``` php
        wfDebugLog( 'ckeditor', $term );
        $originalLink = $parser->parse( '[[File:' . $term . ']]', $wgTitle, $options )->getText();
        wfDebugLog( 'ckeditor', $originalLink );
        if( false == strpos( $originalLink, 'src="' ) ) {
                return '';
        }
```

**Comment by dev-zero** [comment]
I've tried with the master branch, same result.

**Comment by dev-zero** [comment]
ok, closing this as invalid since the problem was the following option in `LocalSettings.php`:

``` php
$wgUrlProtocols[] = 'file:';
```

which should have been

``` php
$wgUrlProtocols[] = 'file://';
```

which made the mediawiki parser go nuts.

**Comment by riparap** [comment]
Clad to hear that you found solution. Thank you for posting the solution too so that issue was not left open and hanging in the air :)
