### ISSUE TITLE
Conflict with external links

### ISSUE THREAD

**Issue by Varlin** [Mediawiki-wysiwyg/WYSIWYG-CKeditor#2]
Adding a simple external link ( not with [http://link] but simply http://link ) causes a bug when saving the page.

The page the begins with :
<parsingerror>...............

**Comment by riparap** [comment]
Possible cause <wbr> tags on page, see details here:
http://www.mediawiki.org/wiki/Extension_talk:WYSIWYG#Conflict_with_simple_url_link_41221
