### ISSUE TITLE
CKEditor references invalid button image from Math extension

### ISSUE THREAD

**Issue by dev-zero** [Mediawiki-wysiwyg/WYSIWYG-CKeditor#24]
`CKeditorParser.body.php` contains:

``` php
$output = '<img _fckfakelement="true" class="FCK__MWMath" _fck_mw_math="'.$content.'" src="'.$wgScriptPath.'/skins/common/images/button_math.png" />';
```

... but since the Math extension is since some time a true extension and not bundled anymore, the file is located here (on my installation):

```
$wgScriptPath.'/extensions/Math/images/button_math.png'
```

This results in a broken image symbol with Chrome and an empty image with Firefox.

**Comment by riparap** [comment]
I do not know how this should be fixed most elegantly... so I did a "quick and dirty" modification, it seems to work in my installation without problems.
