### ISSUE TITLE
Issue with IE 11 user agent matching

### ISSUE THREAD

**Issue by interjinn** [Mediawiki-wysiwyg/WYSIWYG-CKeditor#25]
In ckeditor_php5.php there is the following code to match the newer IE browsers:

``` php
else if ( strpos($sAgent, 'like Gecko') !== false &&  strpos($sAgent, 'Trident/7.0; rv:') !== false  )
```

Unfortunately some software (such as the MSI software on my laptop) add their own garbage to the user agent string and so I have the following (note "MAMI"):

Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; MAMI; rv:11.0) like Gecko

Fortunately it's easy enough to fix by updating your matching logic to the following:

``` php
else if ( strpos($sAgent, 'like Gecko') !== false &&  preg_match( '#Trident/7\.0;.* rv:#', $sAgent ) )
```

Thanks,
Rob.

**Comment by riparap** [comment]
Thanks for providing code for this. File ckeditor_php5.php has been modified.
