### ISSUE TITLE
Empty ordered and bulleted lists dissapear without nbsp after each one

### ISSUE THREAD

**Issue by seankurth** [Mediawiki-wysiwyg/WYSIWYG-CKeditor#28]
Without an nbsp after each empty item, WYSIWYG removes the indents and creates "***" or "###".

**Comment by riparap** [comment]
Sorry, I do not understand the case.. what do you mean by empty item? Where have you created indents, in wysiwyg or in wikitext mode?

Could you post the wikitext code here so I can test it with wysiwyg...

**Comment by seankurth** [comment]
A preloaded template in the preloader extensionwith empty ordered lists in it, such as:
    *
    *
    *
or
    #
    #
    #
will be converted into "***" or "###," which parsed as 3 levels of sublists right next to each other in WYSIWYG. The only way to fix this is by putting &nbsp (deliberately omitted the ; so markdown doesn't try to parse it) after each item. Its a small issue, but its just annoying to create a whole wiki of boilerplates and then have to go back through it and fix the elements that looked great in the template.

**Comment by riparap** [comment]
This has been fixed.
Wysiwyg should now add line feed into wikitext string in case line of bulleted or numbered list in wysiwyg is empty. 

When empty lines are selected in wysiwyg, they will not be marked as selected with blue color as normal text lines. Perhaps easiest way to create empty lists is to but some text on two rows, enter empty lines between them, then select whole block and mark it as numbered or bulleted list and finally remove first and last lines or clear text from them.
