### ISSUE TITLE
Default editor loads before WYSIWYG-CKeditor appears

### ISSUE THREAD

**Issue by lonoak** [Mediawiki-wysiwyg/WYSIWYG-CKeditor#34]
Hi,
   I have just installed the editor and am seeing the original mediawiki editor appears previous to WYSIWYG-CKeditor appearing, how could I fix this?

MediaWiki version: 1.24
WYSIWYG-CKeditor version: github 1.5.6_0 [B551+12.12.2014]

greetings,

j.

**Comment by riparap** [comment]
You should check that settings in your LocalSettings.php are like readme.md of this site suggests and that setting "Start with rich editor disabled" in user prefences of MW for "Editing" is not selected. You should also verify that you have installed modifications of wikieditor extension provided by wysiwyg package.

**Comment by riparap** [comment]
I have not been able to reproduce this in MW 1.22, 1.23 nor 1.24. This has not been reported by others so it propably is some kind of local configuration problem.
