### ISSUE TITLE
Edit text of nowiki and syntaxhighlight tags directly in wysiwyg mode as text (without using image- elements)

### ISSUE THREAD

**Issue by riparap** [Mediawiki-wysiwyg/WYSIWYG-CKeditor#50]
I am trying to modify wysiwyg so that it would be possible to edit texts of  nowiki and syntaxhighlight tags directly on page as text in wysiwyg mode. I am trying to use combination of 

``` javascript
    <pre><nowki>.......</nowiki></pre>
```

and 

``` javascript
    <pre><syntaxhighlight>.......</syntaxhighlight></pre>
```

html tags for this.

It would work so that text will  be first placed on page, then selected and then using some button + dialog combination formatted into nowiki- or syntaxhighlight texts based on user selection.

Couble of questions:
- I am having strange format problems after `<pre>` tag is removed and text becomes normal text again (=when nowiki or syntaxhighlight definition is removed from block of text). Should those strings be enclosed within some extra div- tags or what is the proper way to do it?

``` javascript
    <div><pre><syntaxhighlight>.......</syntaxhighlight></pre></div>
```

``` javascript
    <div><pre><nowiki> ........ </nowiki></pre></div>
```
- How should i use "decodeHtml" / "encodeHtml" commands when taking text from page and inserting it inside  `<pre>....</pre>` tags as text.  I can not figure out what is the proper approach with this.

**Comment by riparap** [comment]
This modification is available for testing under branch "CKeditor_v4_Nowiki-Synt-Pre" (version 1.5.6_0  [B551++26.02.2015]). 

Short instructions:
*Format nowiki/syntaxhighlight can be applied to selected text using button / dialog "Special Texts" of toolbar.
*Existing nowiki/syntaxhighlight format can be edited also using right click of mouse on formatted text block or by double-clicking it. 
*Format nowiki/syntaxhighlight of text block can be seen on lower part of editor window.

If someone prefers old img-element:
*Old img-element with nowiki/syntaxhighlight blocks can be restored into use using variable "$wgFCKEditorSpecialElementWithTextTags = 1;" in LocalSettings.php.

Using tag div must be user selectable action because it has major effects on how text will look like on page. Tag div will not be added by new function.

I am still wondering if this approach is valid.....having own html tags inside document, CKeditor seems to be happy with it. Also converting to/from html may require some more adjustments. Feedback is welcomed.

**Comment by riparap** [comment]
It seems that no html encode/decode calls are needed with this so I have removed them. This has been fixed in version "1.5.6_0  [B551++26.02.2015]".  

As you may already have noticed, I am not an expert with html either :)

**Comment by Varlin** [comment]
I just tried it, and wow, good work !
However, when I test on some page where I already had `<nowiki>` tags, I get problems with newlines.
Where I had a `<nowiki>` tag inline, like...

> You can put text in italic `<nowiki>this way</nowiki>`

now I get 

> You can put text in italic 
> `<nowiki>this way</nowiki>`

EDIT : this is "normal" because `<pre>` tags default display is "block" and not "inline". 
Maybe you could use `<code>` instead ?

**Comment by riparap** [comment]
With style pre.fck_mw_nowiki there is definition "diplay: inline;".

I noticed same thing in wysiwyg mode.... but it did not do it always for me... I could not figure out what is causing this. Have you tried it like this:  format paragraph first with paragraph format "Normal (div)" and then set f.ex nowiki format on text. Does it work any better?

If this happens only in wysiwyg mode it may be because  style definition of wysiwyg pre-styles "pre.fck_mw_nowiki" and "pre.fck_mw_syntaxhighlight" in mediakiki/plugin.js needs some kind of adjustments... I just could not figure out what kind of settings are good there.

One other possibility is that when switching from wysiwyg to wikitext mode and when nowi -tag is processed, extra pre-tag must be "removed" in this case. I do not know how this should be done properly, now it just takes text from child element and pre tag seem to disappear but it may leave extra line feed there instead.

**Comment by Varlin** [comment]
You're right, the style is forced to inline, and the problem is more like an extra line break being added.
I confirm, in a `<div>` paragraph, it seems to work as expected.

But in a "normal" paragraph, in wysiwyg, it breaks it by inserting a line break before and after.
If add `<nowiki>` In source mode inside a "normal" paragraph, when coming back to wysiwyg there is a line break before (but not after !).

**Comment by riparap** [comment]
If  `<div>` tag makes it work, I think extra line feed is not caused by wysiwyg. If line feed was created by wysiwyg, it should appear there no matter where nowiki- format is inserted. 

I have not been able to locate places of creation for extra linefeeds before tag. There are few places where line feed is inserted after tag, but when I tried to remove them, it did not have any positive effect on this problem.

Do you think this issue is a "show stopper" for this modification or do you find this modification usable?

**Comment by Varlin** [comment]
I had some hopes in this [method](http://docs.ckeditor.com/#!/api/CKEDITOR.htmlWriter-method-setRules) but it doesn't seem to work.
Anyway I think it's a good improvement and that we have to keep it ! I even think you can already make it the main branch. And there is still the ability to disable this.
By the way, when you disable it by $wgFCKEditorSpecialElementWithTextTags = 1, you can face a problem : if you double click on a pre tag the screen just become grey (because of the dialog not showing).

**Comment by riparap** [comment]
It is easy to fix double click issue with pre -element in case this feature is disabled.

I will merge this into main branch in near future. There will be some issues with modifications you have made because I have modifed at least one same file as you, but we can worry this later.

**Comment by Varlin** [comment]
I'm a newbie to github (and it's great !) so I don't know if it will be easy or not. Anyway if it's more convenient for you, just merge it and I will do again my pull reuests.

**Comment by riparap** [comment]
These have been fixed in branch CKeditor_v4_Nowiki-Synt-Pre (version: 1.5.6_0 [B551+05.03.2015]):
-double click error of pre- element when "$wgFCKEditorSpecialElementWithTextTags = 1"
-test when wikitext to html conversion can be started "editorSrcToWswTrigger = true" (test of p-tag removed)
-removed one br- tag which caused extra line feeds when toggling source-wysiwyg mode

**Comment by riparap** [comment]
There is only one (two) pull request which I could safely merge in case this branch would be merged into main branch first. All others will have conflicts.  

As far as I know sourcetree which I use with github also requires third party program in order to handle conflicted files. I know that some programmers use kdiff3 for this purpose, because it allows you to compare files in three different locations at same time :)

I think I will merge your pull requests outside github into this test branch first because merging conflicted files will anyway require picking of modified blocks  manually one by one and your modifications seems to be in different parts of files compared to mine.

**Comment by riparap** [comment]
This modification together with modifications made by Varlin has been merged into branch CKeditor_v4. Version 1.5.6_0 [B551+07.03.2015].

I hope everything works properly :)

**Comment by Varlin** [comment]
I tried to replace <pre by <code in function fck_pre_wikiTag, and surprinsingly it fixes the problem of line break before.
