### ISSUE TITLE
Proposal : two icons

### ISSUE THREAD

**Issue by Varlin** [Mediawiki-wysiwyg/WYSIWYG-CKeditor#52]
- I propose to change the blue icon for templates to this one, with "{{ }}" : http://wikirouge.net/nowiki/mediawiki/WYSIWYG/WYSIWYG/ckeditor/plugins/mwtemplate/images/icon_template.gif
  First, for a better visual integration since other tags like <references> are yellow
  Secondly, because the "T" refers to Template in english, but it doesn't make sense in other languages. "{{ }}" seems to me more universal.
- For the same reason of integration, I propose to change the "special icon" so that the background is yellow as the others : http://wikirouge.net/nowiki/mediawiki/WYSIWYG/WYSIWYG/ckeditor/plugins/mediawiki/images/tb_icon_special.gif

**Comment by riparap** [comment]
I agree with "T" inside button. Based on your suggestion I took liberty to do it in slightly different way, you can find example for button of  template dialog with modification for "nowiki/syntaxhighlight -tags" in branch "CKeditor_v4_Nowiki-Synt-Pre".  I prefer "plain" style of buttons, yellow color is little bit too bright for my straight-faced personality :).

**Comment by Varlin** [comment]
ok, I agree that's better when it's sober :)
the color of the fake element put inside the editor should correspond however, but it will depend on how we succeed in implementing editable fake elements like `<nowiki>`
