### ISSUE TITLE
No more word-wrap in wikitext view

### ISSUE THREAD

**Issue by Varlin** [Mediawiki-wysiwyg/WYSIWYG-CKeditor#62]
I just noticed that I have no more word-wrap in wikitext view. I don't know what changes could have caused that. 

Is it the same for you or is it just me ?

**Comment by riparap** [comment]
In source mode of wysiwyg window word at end of line can be splitted at any point in the middle of the word based on width of browser window = it does not keep words on end of line complete. I have never before payed any attention on this in source mode of wysiwyg.

In wysiwyg mode, word is kept whole and they are not splitted in two parts.

I have not changed anything related directly to this, but of cource it is always possible that some of the modifications may have had indirect effect on this....but I somehow doubt it, unless perhaps format for pre tag for nowiki/syntaxhighlight tags, in case you are using branch CKeditor_v4_Nowiki-Synt-Pre.

Which branch are you using: CKeditor_v4_Nowiki-Synt-Pre or CKeditor_v4?

**Comment by Varlin** [comment]
I don't know exactly what are the correct terms in english, but I was not
speaking of "word break", but of "line break" (the lines are not broken and
there is an horizontal scrollbar until there is a "hard" line break).

In fact, the problem is due to a recent Firefox update (https://support.mozilla.org/fr/questions/1050456).

**Comment by riparap** [comment]
Ok...I see. It seems to work like that in FF v36.0.1. In IE11 this problem does not exist.

Can this be fixed by modifying styles in ckeditor/contents.css to include "style="white-space: pre-wrap;", which has been mentioned in abowe thread.

**Comment by Varlin** [comment]
Yes, it works. And by the way, this fix at the same time the problem of word breaking with IE.
I propose to correct it in editor.css, instead of content.css, because it is upstream and it avoids the need to override a css style by another.
https://github.com/Mediawiki-wysiwyg/WYSIWYG-CKeditor/pull/63

**Comment by riparap** [comment]
Sound good that you found a fix but modified files, as well as the one I proposed earlier "contents.css",  are core files of CKeditor and I still do not like the idea of editing them directly. 

My opinion is that best fix for these should be some kind of override definition which then could be specific for wysiwyg only. That way it would be immune to possible updates that may happen with CKeditor.

**Comment by Varlin** [comment]
Yes and no, because there is no more skins/kama in main CKeditor project, so it will not make conflict.

EDIT : I'm wrong it is not in the basic package but it is still available for download. Anyway, I reported this bug, let's see if this modification is accepted by ckeditor devs !
http://dev.ckeditor.com/ticket/13031

**Comment by riparap** [comment]
I have created new branch CKeditor_v4_Test to make it easier to manage pull request and to keep main branch Ckeditor as "stable" release.

Would it be possible for you to cancel all your pull requests against branch CKeditor_v4 and recreate them against this new branch CKeditor_v4_Test ?

**Comment by Varlin** [comment]
it has been included if official CKeditor version : http://dev.ckeditor.com/ticket/13031

**Comment by riparap** [comment]
I will not merge this modification because modified files are files of CKeditor.

This is not anymore an issue in version 1.5.6_0 [B551+07.07.2015] of branch CKeditor_v45, which includes update of CKeditor from version 4.4.5 to versions 4.5.1.

**Comment by riparap** [comment]
Fixed after upgrading CKeditor to version 4.5.1.
