### ISSUE TITLE
<br/> is replicated when toggled between WYSIWYG and wiki editor

### ISSUE THREAD

**Issue by ajithijk** [Mediawiki-wysiwyg/WYSIWYG-CKeditor#73]
If there is a `<br/>` in the page , the toggling between wikieditor and WYSIWYG replicates that and a large number of `<br/>` is coming. tried with the latest ckeditor version 4.4.5 .

**Comment by ajithijk** [comment]
Pasting above notes with quotes as it is not displayed properly.
If there is a "<br/>" in the page , the toggling between wikieditor and WYSIWYG replicates that and a large number of "<br/>" is coming. tried with the latest ckeditor version 4.4.5 .

**Comment by riparap** [comment]
I tried to insert few `<br/>` tags on page between text lines in source view and  then toggled between wysiwyg and source modes, but I can not reproduce this with wysiwyg version "1.5.6_0 [B551+13.03.2015]" + IE11 or FF 36.0.4.

However it behaves slightly different way in case you have only `<br/>`  compared to when you have line feed + `<br/>` between text lines.

Version of ckeditor does not provide anough information, could you check MW page "special:versions" what is the version of your wysiwyg bundle. What browser version are you using? Could you provide sample wikitext code of your test page where it behaves weirdly?

**Comment by ajithijk** [comment]
Hi ,

Thank you for looking into this. We found out the issue. When we use html tidy this is coming into picture. When tidy is disabled the extra `<br/>`'s are not coming. But I believe there should be a way in which the tidy can be used without causing any extra `<br/>` . Any information on that would be really helpful. You can see this coming by just drawing a table and then toggle the WYSIWYG editor to wiki editor and back. The WYSIWYG version I tried is with "1.5.6_0 [B551], based on this version, modified further, using CKEditor 4.4.4 (revision 1ba5105)" and also with "1.5.6_0 [B551+13.03.2015], CKEditor 4.4.5 [revision 25cdcad]"

**Comment by riparap** [comment]
I do not know anything about html tidy. How have you integrated it with MW ? ... or is it somehow integrated with CKeditor within wysiwyg?

**Comment by ajithijk** [comment]
I have integrated that with MW using $wgUseTidy = true; and configuring html tidy using php. I could see in CKeditor  calls some of the tidy functions. Is that the same html tidy or is it different .Eg:- setTidy in WYSIWYG/CKeditorEditPage.body.php

**Comment by riparap** [comment]
Unfortunatedly I am not familar with this function nor purpose of it.
