### ISSUE TITLE
Editing links without changes clears the link name

### ISSUE THREAD

**Issue by hst88** [Mediawiki-wysiwyg/WYSIWYG-CKeditor#76]
When you create an external link and edit it (without any changes), the name of the link disappears (Displays "[1]").

**Comment by riparap** [comment]
I can not reproduce this in my system (version 1.5.6_0 [B551+13.03.2015] with IE11.0.9600.17843 or FF 39.0). To me it seems like creation of external link (and saving the page) works (link may either have different display text or identical with text of link). 

It may be caused either by contents of the link itself or by display text you entered or by the way how you edit existing external link.

Only if I open page with existing external link (=link must have identical display text as what is link text), go to edit mode and double click the link and then save it without editing link value and then save the page => displayed text on page will be something like "[1]".  Can you verify if this is the case also in your system?

**Comment by riparap** [comment]
This has been changed in version 1.5.6_0 [B551+07.07.2015] ...can be found in branch CKeditor_v45 at this moment, this includes also update of CKeditor from version 4.4.5 to 4.5.1.
