### ISSUE TITLE
Table inscription (|+) doesn't work

### ISSUE THREAD

**Issue by hst88** [Mediawiki-wysiwyg/WYSIWYG-CKeditor#78]
When I use "|+" for a table inscription the editor crashes with error "TypeError: htmlNode is undefined". Why I can't disable the editor in this case?

**Comment by riparap** [comment]
How have you entered that value in table... have you used wikitext mode for that? ... so error happens when you open wiki page where there is that syntax in table, causing wysiwyg editor to crash ?

**Comment by hst88** [comment]
The error happens when I change from wysiwyg editor to the "normal" editor.
You can use the following code to test it:
{| width="100%" border="1" cellpadding="0" cellspacing="1"
|+ Test 
|-
! scope="col" | Test
! scope="col" | Test
|}
Now when you change to the wysiwyg editor anything seems to be ok but you can't disable the editor again.
In our case someone saved the page and then all links on the page were broken.

**Comment by riparap** [comment]
This has been fixed in version 1.5.6_0 [B551+30.10.2015]. Based on my tests it should now be able to handle all table examples of page mediawiki.org Help:Tables.
