### ISSUE TITLE
WYSIWYG editor removes leading spaces

### ISSUE THREAD

**Issue by knoxg** [Mediawiki-wysiwyg/WYSIWYG-CKeditor#79]
Mediawiki will render lines with a leading space in a PRE HTML block, but still allow wiki markup within the block, e.g.

```
this line starts at column 1

    this line starts at column 4 and '''this bit is in bold'''
      this is at column 6
    and this is at 4 again

back to normal
```

If the text above is entered (using the 'Source' entry method), and saved, then the page appears as desired. 

When 'Edit' is clicked, the WYSIWYG editor displays the text correctly, but once the page is saved, the "this is at column 6" and "and this is at 4 again" lines above have moved to the left one column (i.e. they visually appear at column 5 and column 3). The first row appears correctly.

Every time the page is modified, the second (and following) lines of any block with leading spaces are shifted to the left by one character, until eventually, all lines align with the left margin.

It would be nice if this didn't happen (i.e. identation is preserved during WYSIWYG edits).

**Comment by knoxg** [comment]
Looks like this has been happening for a while ( similar issue from Feb 2012: https://www.mediawiki.org/wiki/Thread:Project:Support_desk/stop_erasing_leading_blank_space_in_every_line/reply_%283%29 )

**Comment by riparap** [comment]
Example text:

```
this line starts at column 1

 this line starts with 1 space in wikitext mode
    this line starts with 4 spaces in wikitext mode and '''this bit is in bold'''
      this starts with 6 spaces in wikitext mode
    and this line starts again with 4 spaces  in wikitext mode
 this line starts with 1 space  in wikitext mode

back to column 1 again
```

Text above contains lines which starts with spaces if viewed in mediawiki wikitext mode. When text is displayed in browser as mediawiki html, each line has lost one space at beginning of line yet indent is such that it looks like lines have original amount of spaces. This is normal MW behaviour.

Same html output which is already missing one space with each line is then taken into WYSIWYG edit mode as it is. This means that we loose one space at beginning of each line already when page is opened in wysiwyg mode. It looks like wysiwyg is not able to fix this exeption when page is saved or source button is pressed.

I guess I have found a fix for this.... I have to test this little more first.

**Comment by riparap** [comment]
I have made a modification for this in Version 1.5.6_0 [B551+29.11.2015].

**Comment by knoxg** [comment]
Have downloaded and installed the latest WYSIWYG-CKeditor code into my wiki installation and the fix works for me.

Thanks !
