### ISSUE TITLE
How did you manage to add a lang ?

### ISSUE THREAD

**Issue by Varlin** [Mediawiki-wysiwyg/WYSIWYG-CKeditor#8]
Hi,
I tried to mimic what you did with finnish to add french, but I fail.
I probably missed some change you made in a file, but can't guess which. Have you an idea ?

**Comment by riparap** [comment]
Problem was with CKeditor build config, I had not included all the available languages of CKeditor there. I did not find a way how to add languages later in CKeditor config so I reupdated CKeditor 4.3.4 in branch CKeditor_v4 (=rebuild the download pakage of CKeditor with all languages). I hope it will now work better with french too.

**Comment by Varlin** [comment]
Yes thanks it works fine !
