### ISSUE TITLE
Spell Checker Parser

### ISSUE THREAD

**Issue by 0x539-nero** [Mediawiki-wysiwyg/WYSIWYG-CKeditor#85]
Is there anyway to parse what is in the CK-editor instead of the Wiki code?

Thank you.

**Comment by riparap** [comment]
Do you mean that you would like to use some spell checker- plugin inside wyiwyg editing window?

**Comment by 0x539-nero** [comment]
Yes.

**Comment by 0x539-nero** [comment]
Instead of searching through the MediaWiki code.

**Comment by riparap** [comment]
There is SCAYT plugin of CKeditor included with wysiwg bundle (3. button of toolbar from left on upper line, ABC Spell Checker). Is this what you are looking for?

**Comment by 0x539-nero** [comment]
Yes I use that but it literally checks through all the wiki code. I want it to just check the actual text instead of look through the wikicode (which is really messy)

**Comment by riparap** [comment]
SCAYT seems to do so, it does not know which part of text belongs to special elements of wysiwyg mode which may contain text in wikitext format. I do not know any other plugin and if there is I quess they will work similarly. To alter SCAYT behaviour would mean modifications to that plugin.

**Comment by 0x539-nero** [comment]
Yes, and I was asking about that; if there isn't a quick fix, then don't worry about it. Thanks!
