### ISSUE TITLE
Branch mediawiki_mw127_459: widgets, change of dataprocessor (Version >= 1.5.6_0 [B551+20.07.2016]):

### ISSUE THREAD

**Issue by riparap** [Mediawiki-wysiwyg/WYSIWYG-CKeditor#90]
Two (2) major modifications  included in branch mediawiki_mw127_459 (=>Version 1.5.6_0 [B551+20.07.2016]):
1. Update of CKEditor from version CKeditor 4.5.8 [revision c1fc9a9] to CKEditor 4.5.9 (revision a35abfe), added Widget- plugin (runtime- and source- files).
2. Replaced custom dataprocessor of Wysiwyg by standard dataprocessor of CKeditor: advanced content filtering (ACF) of CKeditor will now work (at this moment all kind of content is allowed by setting "config.allowedContent = true;" of config.js), this will also provide possibility for other plugins to work properly with Wysiwyg (f.ex Widget- plugin).

Modification related to new widget- plugin:
3. Elements related to references (Cite- extension, ref- and references tags) in Wysiwyg- mode are now widgets: drag and drop of these elements is supported, elements are protected so that they can not be tampered with by mistake.

**Comment by Varlin** [comment]
Hi Riparap. I'm updating all my wiki and I discover all the great improvements you've done to this extension! Wow ! This one with references as widgets is so cool :) 

I have a question regarding the button "MWReferencesUpd" : it seems that your code automagically convert old references into new ones, so is it still useful ?

I just noticed one bug : if I double click on the footnotes, I get a frozen grayed (disabled) screen, like if a dialog tried to pop up but doesn't pop up. Do you have same behaviour ?

Thanks

**Comment by riparap** [comment]
Thanks :)     Widgets are really neat thing.  Widgets of references is adapted to use the old ref- dialog and is a little bit customized solution compared to tutorials of widgets from CKeditor.

Button "MWReferencesUpd" is usefull in case you have f.ex two references- placeholders on page and if first one of them is removed, in this case case remaining references- placeholder  will not be updated automatically in wysiwyg- mode.

**Comment by riparap** [comment]
Double clicking references- placeholder did behave like you  say when you double-click references- placeholder after page is opened in wysiwyg mode (existing references- tag on page). If new references- placeholder is added and if this is double clicked immediatedly, it opens empty ref- dialog. 

There was couble of errors with definition of widget for references- placeholder. This has been fixed in "Version 1.5.6_0 [B551+09.08.2016]".

**Comment by Varlin** [comment]
Next step : make the references directly editable :)

**Comment by riparap** [comment]
Footnotes plugin of CKeditor does that, but because mediawiki does not store texts of references that way I desided to stick with old style because it was more straightforward and easier way to make widget work.  

Making references placeholder editable might be possible but it will then require all kind of other changes too to reflect that change into ref- elements around the document.
