### ISSUE TITLE
Use of "CKEDITOR_BASEPATH" is deprecated. Use mw.config

### ISSUE THREAD

**Issue by Wingsofcourage** [Mediawiki-wysiwyg/WYSIWYG-CKeditor#95]
Mediawiki 1.25 and latest mw127_459 branch show:

load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=WHYBlfds:156 Use of "CKEDITOR_BASEPATH" is deprecated. Use mw.config

I changed from:

WYSIWYG/ckeditor/ckeditor.jsckeditor/ckeditor.js:(function(){if(window.CKEDITOR&&window.CKEDITOR.dom)return;window.CKEDITOR||(window.CKEDITOR=function(){var a=/(^|.*[\\\/])ckeditor\.js(?:\?.*|;.*)?$/i,d={timestamp:"G4CD",version:"4.5.9",revision:"a35abfe",rnd:Math.floor(900*Math.random())+100,_:{pending:[],basePathSrcPattern:a},status:"unloaded",basePath:function(){var **b=window.CKEDITOR_BASEPATH**||"";if(!b)for(var c=document.getElementsByTagName("script"),d=0;d<c.length;d++){var k=c[d].src.match(a);if(k){b=k[1];break}}-1==b.indexOf(":/")&&"//"!=b.slice(0,2)&&(b=0===b.indexOf("/")?location.href.match(/^.*?:\/\/[^\/]*/)[0]+

to:
extensions/WYSIWYG/ckeditor/ckeditor.js:(function(){if(window.CKEDITOR&&window.CKEDITOR.dom)return;window.CKEDITOR||(window.CKEDITOR=function(){var a=/(^|.*[\\\/])ckeditor\.js(?:\?.*|;.*)?$/i,d={timestamp:"G4CD",version:"4.5.9",revision:"a35abfe",rnd:Math.floor(900*Math.random())+100,_:{pending:[],basePathSrcPattern:a},status:"unloaded",basePath:function(){var **b=mw.config.get('CKEDITOR_BASEPATH')**||"";if(!b)for(var c=document.getElementsByTagName("script"),d=0;d<c.length;d++){var k=c[d].src.match(a);if(k){b=k[1];break}}-1==b.indexOf(":/")&&"//"!=b.slice(0,2)&&(b=0===b.indexOf("/")?location.href.match(/^.*?:\/\/[^\/]*/)[0]+

and the error is gone.

**Comment by riparap** [comment]
I agree, that is how MW wants it. However, that file is unmodified core file of ckeditor and in case version of ckeditor will be updated, this problem will be back. Is it so that editing source files of ckeditor is the only way to fix this issue also with new versions of ckeditor?

**Comment by Wingsofcourage** [comment]
ok
