### ISSUE TITLE
Blank window with background color with mw 1.27.1 and mw127_459 branch

### ISSUE THREAD

**Issue by Wingsofcourage** [Mediawiki-wysiwyg/WYSIWYG-CKeditor#97]
Hi 

I'm a little bit confused with latest Mediawiki 1.27.1 and latest from mv127_459 branch.
I see only a large inner frame with background color with no content.
I use RHEL 7.2 with PHP 5.5
PHP 5.5.38 (cli) (built: Jul 21 2016 12:25:20)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies

LocalSettings contains:
wfLoadExtension( 'WYSIWYG' );
wfLoadExtension( 'WikiEditor' );

Did i missed something ?
Any ideas for debugging ?
If i inspect the content of the frame i see that the text is there, but the content is disabled by css and the buttons are only text. 

Thanks.

**Comment by Wingsofcourage** [comment]
I updated to RHEL 7.3 and PHP 7
still a blank window for WYSIWYG.

**Comment by Wingsofcourage** [comment]
Made the same installation on Ubuntu server 16.04.1 LTS and it works like a charm. 
What i see is, that there is no ICU version displayed on the version information page.
Is there a dependency in CKeditor to a certain ICU version ?

**Comment by Wingsofcourage** [comment]
This must be a server config issue. I nailed it down to this error after cleaning all caches.
load.php?debug=false&lang=en&modules=ext.CKEDITOR|ext.WYSIWYG.func&skin=vector&version=48b86572c613:34 **Resource interpreted as Stylesheet but transferred with MIME type text/plain**: "http://idaawiki.dst.ibm.com/extensions/WYSIWYG/ckeditor/contents.css?t=G4CD".

**Comment by Wingsofcourage** [comment]
Finally i found it.
/etc/mime.types doesn't contain the following line:

text/css                                        css

Therefore the http server was not able to send css files with the correct mime type.

**Comment by riparap** [comment]
I have used only Centos 6.x versions with wysiwyg. Thank you for instructions how to fix this.
